[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  included_files = ["src/lib/**"]

[functions."check-crnata"]
  schedule = "*/15 * * * *"

[functions."clean-logs"]
  schedule = "0 1 * * *"